
sims-now :
	$(MAKE) -C none-none sims-now
	$(MAKE) -C lo-lo sims-now
	$(MAKE) -C med-med sims-now
	$(MAKE) -C hi-hi sims-now

report :
	$(MAKE) -C none-none report
	$(MAKE) -C lo-lo report
	$(MAKE) -C med-med report
	$(MAKE) -C hi-hi report

clean :
	$(MAKE) -C none-none clean
	$(MAKE) -C lo-lo clean
	$(MAKE) -C med-med clean
	$(MAKE) -C hi-hi clean

preen :
	$(MAKE) -C none-none preen
	$(MAKE) -C lo-lo preen
	$(MAKE) -C med-med preen
	$(MAKE) -C hi-hi preen
	rm -rf *.bak
	rm -rf *~
