###############################################################################
# Moleculizer - a stochastic simulator for cellular chemistry.
# Copyright (C) 2001  Walter Lawrence (Larry) Lok.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    
# Contact information:
#   Larry Lok, Research Fellow          Voice: 510-981-8740
#   The Molecular Sciences Institute      Fax: 510-647-0699
#   2168 Shattuck Ave.                  Email: lok@molsci.org
#   Berkeley, CA 94704
###############################################################################

# This demo seems to be regression for continuator.

DEMO_NAME := heinrich-state

DEMO_DIR := $(DEMO)/$(DEMO_NAME)

# No explanation for this variation, except that the simulation seems to be
# the same old heinrich.
INPUT_FILE := $(DEMO_DIR)/heinrich.xml

DOC_INPUT_HTML := $(DEMO_DIR)/source.html

CTR_OUTPUT_DIR := $(DEMO_DIR)/$(DEMO_NAME).out

MZR_OUTPUT_DIR := $(DEMO_DIR)/heinrich.out

MZR_STATE_FILE := $(MZR_OUTPUT_DIR)/param-dump.xml

$(DEMO_DIR)/target : $(CTR_OUTPUT_DIR)/simulation-done $(DOC_INPUT_HTML)

$(MZR_OUTPUT_DIR) :
	mkdir $@

# Do a moleculizer run that generates a state dump.
$(MZR_OUTPUT_DIR)/simulation-done : MSF := $(MZR_STATE_FILE)
$(MZR_OUTPUT_DIR)/simulation-done : $(INPUT_FILE) | $(MZR_OUTPUT_DIR)
	echo "Started at" `date` > $@
	cp $< $(@D)
	cd $(@D) \
	&& moleculizer < $(<F) \
	&& parametrizer heinrich-state.xml < $(<F) > $(notdir $(MSF)) \
	&& plot-dmp-files
	echo "Finished at" `date` >> $@

$(CTR_OUTPUT_DIR) :
	mkdir $@

# Do a continuator run with the state dump generated by Moleculizer.
$(CTR_OUTPUT_DIR)/simulation-done : MSF := $(MZR_STATE_FILE)
$(CTR_OUTPUT_DIR)/simulation-done : $(INPUT_FILE) \
	$(MZR_OUTPUT_DIR)/simulation-done \
	| $(CTR_OUTPUT_DIR)
	echo "Started at " `date` > $@
	cp $(MSF) $(@D)
	cp $< $(@D)
	cd $(@D) \
	&& continuator $(notdir $(MSF)) < $(<F) \
	&& plot-dmp-files
	echo "Finished at " `date` >> $@

# Make documented html version of input file.
# 
# I'm somewhat uncomfortable using this relative path for the documentation
# URL.
$(DOC_INPUT_HTML) : FLAT_DOC_URL := ../../doc/static-doc/
$(DOC_INPUT_HTML) : $(INPUT_FILE)
	java org.apache.xalan.xslt.Process \
	-in $< \
	-xsl $(XSL)/arg-mzr2static-doc.xsl \
	-param flat-doc-url $(FLAT_DOC_URL) \
	-param caption $(<F) \
	-html \
	-out $@

# For running the demo several times.
$(DEMO_DIR)/clean : CLN := $(CTR_OUTPUT_DIR) \
	$(MZR_OUTPUT_DIR) \
	$(DOC_INPUT_HTML)
$(DEMO_DIR)/clean :
	rm -rf $(CLN)

CLEAN_LIST += $(CTR_OUTPUT_DIR) \
	$(MZR_OUTPUT_DIR) \
	$(DOC_INPUT_HTML)

PREEN_LIST += $(DEMO_DIR)/*~ $(DEMO_DIR)/*.bak
