###############################################################################
# Moleculizer - a stochastic simulator for cellular chemistry.
# Copyright (C) 2001  Walter Lawrence (Larry) Lok.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    
# Contact information:
#   Larry Lok, Research Fellow          Voice: 510-981-8740
#   The Molecular Sciences Institute      Fax: 510-647-0699
#   2168 Shattuck Ave.                  Email: lok@molsci.org
#   Berkeley, CA 94704
###############################################################################

DEMO_NAME := simple-odie

DEMO_DIR := $(DEMO)/$(DEMO_NAME)

ODIE_INPUT_FILE := $(DEMO_DIR)/$(DEMO_NAME).xml

ODIE_TMP_INPUT_FILE := $(DEMO_DIR)/$(DEMO_NAME)-tmp.xml

ODIE_OUTPUT_DIR := $(DEMO_DIR)/$(DEMO_NAME).out

MZR_INPUT_FILE := $(DEMO_DIR)/simple.xml

MZR_OUTPUT_DIR := $(DEMO_DIR)/simple.out

$(DEMO_DIR)/target : $(ODIE_OUTPUT_DIR)/simulation-done

$(DEMO_DIR)/input : $(ODIE_TMP_INPUT_FILE)

$(ODIE_OUTPUT_DIR) :
	mkdir $@

# Use reaction network generated by a moleculizer simulation
# as input to an ODE simulation.
$(ODIE_OUTPUT_DIR)/simulation-done : $(ODIE_INPUT_FILE) | $(ODIE_OUTPUT_DIR)
	echo "Started at" `date` > $@
	cp $< $(@D)
	cd $(@D) \
	&& odie < $(<F) \
	&& plot-dmp-files-as-cnc
	echo "Finished at" `date` >> $@

# Transform reparamterized reaction network (state dump) into an odie input
# file.  This file still requires some editing of a few odie-specific
# parameters before running.
$(ODIE_TMP_INPUT_FILE) : $(MZR_OUTPUT_DIR)/simulation-done
	state2odie $(<D)/param-dump.xml $@

$(MZR_OUTPUT_DIR) :
	mkdir $@

# Run moleculizer simulation to generate reaction network
$(MZR_OUTPUT_DIR)/simulation-done : $(MZR_INPUT_FILE) | $(MZR_OUTPUT_DIR)
	echo "Started at" `date` > $@
	cp $< $(@D)
	cd $(@D) \
	&& moleculizer < $(<F) \
	&& parametrizer state-dump.xml < simple.xml > param-dump.xml \
	&& plot-dmp-files
	echo "Finished at" `date` >> $@

# For redoing the demo several times.
$(DEMO_DIR)/clean : CLN := $(ODIE_OUTPUT_DIR) \
	$(MZR_OUTPUT_DIR) \
	$(ODIE_TMP_INPUT_FILE)
$(DEMO_DIR)/clean :
	rm -rf $(CLN)

CLEAN_LIST += $(ODIE_OUTPUT_DIR) \
	$(MZR_OUTPUT_DIR) \
	$(ODIE_TMP_INPUT_FILE)

PREEN_LIST += $(DEMO_DIR)/*~ $(DEMO_DIR)/*.bak
