<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
><xsl:param name="path-doc-url"
/><xsl:param name="caption" select="'An XML Document'"
/><xsl:template match="*"
><xsl:param name="xpth"
/><xsl:variable name="curpth" select="concat($xpth, name())"
/><xsl:element name="li"
><xsl:element name="a"
><xsl:attribute name="href"
><xsl:value-of select="concat($path-doc-url, $curpth)"
/></xsl:attribute><xsl:element name="strong"
><xsl:value-of select="name()"
/></xsl:element></xsl:element><xsl:if test="@*"
><xsl:element name="table"
><xsl:attribute name="border"
><xsl:text
>1</xsl:text></xsl:attribute><xsl:element name="tr"
><xsl:element name="td"
><xsl:text
>Attribute</xsl:text></xsl:element><xsl:element name="td"
><xsl:text
>Value</xsl:text></xsl:element></xsl:element><xsl:for-each select="@*"
><xsl:element name="tr"
><xsl:element name="td"
><xsl:element name="a"
><xsl:attribute name="href"
><xsl:value-of select="concat($path-doc-url, $curpth, '/@', name())"
/></xsl:attribute><xsl:value-of select="name()"
/></xsl:element></xsl:element><xsl:element name="td"
><xsl:value-of select="."
/></xsl:element></xsl:element></xsl:for-each></xsl:element></xsl:if><xsl:if test="*"
><xsl:element name="ul"
><xsl:apply-templates
><xsl:with-param name="xpth" select="concat($curpth, '/')"
/></xsl:apply-templates></xsl:element></xsl:if></xsl:element></xsl:template><xsl:template match="/"
><xsl:element name="head"
><xsl:element name="title"
><xsl:value-of select="$caption"
/></xsl:element></xsl:element><xsl:element name="body"
><xsl:element name="H1"
><xsl:value-of select="$caption"
/></xsl:element><xsl:element name="ul"
><xsl:apply-templates
><xsl:with-param name="xpth" select="'/'"
/></xsl:apply-templates></xsl:element></xsl:element></xsl:template></xsl:stylesheet>