#!/bin/bash
###############################################################################
# Moleculizer - a stochastic simulator for cellular chemistry.
# Copyright (C) 2001  Walter Lawrence (Larry) Lok.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    
# Contact information:
#   Larry Lok, Research Fellow          Voice: 510-981-8740
#   The Molecular Sciences Institute      Fax: 510-647-0699
#   2168 Shattuck Ave.                  Email: lok@molsci.org
#   Berkeley, CA 94704
###############################################################################

# This plots all the .dmp files in the current directory to .png graphics
# files, but with the assumption that the contents of the dmp files
# are really concentrations.

# When a Moleculizer state dump is converted to odie input, the dump file
# names aren't changed from ".dmp" to ".cnc" as one might desire.  This
# just lets you plot the .dmp output files from odie as the concentrations
# that they are.

# The "test" avoids generating a file named "*.png" when there are no .dmp
# files, so that "dumpfile" is bound to the string "*.dmp".
for dumpfile in *.dmp
do
test -r $dumpfile && plt -n -y 'Concentration in moles/liter' $dumpfile > ${dumpfile%.dmp}.png
done
